name = "HermiteNormalForm"
uuid = "2831c214-8828-4f57-be2f-61bd9bc58165"
authors = ["Yingbo Ma <mayingbo5@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
